version: '3.8'

services:
  mysql:
    image: mysql:8.0.36
    container_name: mysql-local
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: task_tracker
    command:
      [
        "--default-authentication-plugin=mysql_native_password",
        "--lower-case-table-names=2"
      ]
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -proot"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  mysql_data:
    name: mysql_data

networks:
  default:
    name: mysql_network
    driver: bridge
